version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: safe_screen_postgres
    restart: always
    environment:
      POSTGRES_USER: safe_screen_user
      POSTGRES_PASSWORD: safe_screen_password
      POSTGRES_DB: safe_screen_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
